package fv

// the references, in order, of the Foundation set of Fighter Verses
var FoundationSet = []entry{
	{BibleOrder: 1, SetOrder: 1, Set: "Foundation", Ref: "Genesis 1:1"},
	{BibleOrder: 50, SetOrder: 2, Set: "Foundation", Ref: "Matthew 6:24"},
	{BibleOrder: 39, SetOrder: 3, Set: "Foundation", Ref: "Proverbs 3:5"},
	{BibleOrder: 19, SetOrder: 4, Set: "Foundation", Ref: "Psalm 1:6"},
	{BibleOrder: 48, SetOrder: 5, Set: "Foundation", Ref: "Isaiah 30:15"},
	{BibleOrder: 49, SetOrder: 6, Set: "Foundation", Ref: "Isaiah 43:5"},
	{BibleOrder: 31, SetOrder: 7, Set: "Foundation", Ref: "Psalm 119:105"},
	{BibleOrder: 47, SetOrder: 8, Set: "Foundation", Ref: "Proverbs 30:5"},
	{BibleOrder: 12, SetOrder: 9, Set: "Foundation", Ref: "1 Chronicles 16:34"},
	{BibleOrder: 37, SetOrder: 10, Set: "Foundation", Ref: "Proverbs 1:7"},
	{BibleOrder: 21, SetOrder: 11, Set: "Foundation", Ref: "Psalm 56:3"},
	{BibleOrder: 32, SetOrder: 12, Set: "Foundation", Ref: "Psalm 121:1-2"},
	{BibleOrder: 33, SetOrder: 13, Set: "Foundation", Ref: "Psalm 121:3-4"},
	{BibleOrder: 34, SetOrder: 14, Set: "Foundation", Ref: "Psalm 121:5-6"},
	{BibleOrder: 35, SetOrder: 15, Set: "Foundation", Ref: "Psalm 121:7"},
	{BibleOrder: 36, SetOrder: 16, Set: "Foundation", Ref: "Psalm 121:8"},
	{BibleOrder: 22, SetOrder: 17, Set: "Foundation", Ref: "Psalm 86:7"},
	{BibleOrder: 44, SetOrder: 18, Set: "Foundation", Ref: "Proverbs 18:10"},
	{BibleOrder: 23, SetOrder: 19, Set: "Foundation", Ref: "Psalm 95:3"},
	{BibleOrder: 71, SetOrder: 20, Set: "Foundation", Ref: "James 1:17"},
	{BibleOrder: 2, SetOrder: 21, Set: "Foundation", Ref: "Exodus 20:2-3"},
	{BibleOrder: 3, SetOrder: 22, Set: "Foundation", Ref: "Exodus 20:4"},
	{BibleOrder: 4, SetOrder: 23, Set: "Foundation", Ref: "Exodus 20:7"},
	{BibleOrder: 5, SetOrder: 24, Set: "Foundation", Ref: "Exodus 20:8"},
	{BibleOrder: 6, SetOrder: 25, Set: "Foundation", Ref: "Exodus 20:12"},
	{BibleOrder: 7, SetOrder: 26, Set: "Foundation", Ref: "Exodus 20:13-15"},
	{BibleOrder: 8, SetOrder: 27, Set: "Foundation", Ref: "Exodus 20:16"},
	{BibleOrder: 9, SetOrder: 28, Set: "Foundation", Ref: "Exodus 20:17a"},
	{BibleOrder: 13, SetOrder: 29, Set: "Foundation", Ref: "Joshua 1:9"},
	{BibleOrder: 62, SetOrder: 30, Set: "Foundation", Ref: "Ephesians 6:1"},
	{BibleOrder: 14, SetOrder: 31, Set: "Foundation", Ref: "Psalm 1:1"},
	{BibleOrder: 15, SetOrder: 32, Set: "Foundation", Ref: "Psalm 1:2"},
	{BibleOrder: 16, SetOrder: 33, Set: "Foundation", Ref: "Psalm 1:3"},
	{BibleOrder: 17, SetOrder: 34, Set: "Foundation", Ref: "Psalm 1:4"},
	{BibleOrder: 18, SetOrder: 35, Set: "Foundation", Ref: "Psalm 1:5"},
	{BibleOrder: 19, SetOrder: 36, Set: "Foundation", Ref: "Psalm 1:6"},
	{BibleOrder: 70, SetOrder: 37, Set: "Foundation", Ref: "Hebrews 13:16a"},
	{BibleOrder: 45, SetOrder: 38, Set: "Foundation", Ref: "Proverbs 19:20"},
	{BibleOrder: 20, SetOrder: 39, Set: "Foundation", Ref: "Psalm 36:5"},
	{BibleOrder: 38, SetOrder: 40, Set: "Foundation", Ref: "Proverbs 1:10"},
	{BibleOrder: 61, SetOrder: 41, Set: "Foundation", Ref: "2 Corinthians 10:17"},
	{BibleOrder: 56, SetOrder: 42, Set: "Foundation", Ref: "Romans 12:21"},
	{BibleOrder: 41, SetOrder: 43, Set: "Foundation", Ref: "Proverbs 15:1"},
	{BibleOrder: 52, SetOrder: 44, Set: "Foundation", Ref: "Luke 18:27"},
	{BibleOrder: 53, SetOrder: 45, Set: "Foundation", Ref: "John 3:16"},
	{BibleOrder: 24, SetOrder: 46, Set: "Foundation", Ref: "Psalm 100:1-2"},
	{BibleOrder: 25, SetOrder: 47, Set: "Foundation", Ref: "Psalm 100:3"},
	{BibleOrder: 28, SetOrder: 48, Set: "Foundation", Ref: "Psalm 100:4"},
	{BibleOrder: 26, SetOrder: 49, Set: "Foundation", Ref: "Psalm 100:5"},
	{BibleOrder: 73, SetOrder: 50, Set: "Foundation", Ref: "James 4:7-8a"},
	{BibleOrder: 40, SetOrder: 51, Set: "Foundation", Ref: "Proverbs 3:11-12"},
	{BibleOrder: 74, SetOrder: 52, Set: "Foundation", Ref: "1 Peter 5:7"},
	{BibleOrder: 67, SetOrder: 53, Set: "Foundation", Ref: "Philippians 4:11b"},
	{BibleOrder: 46, SetOrder: 54, Set: "Foundation", Ref: "Proverbs 29:11"},
	{BibleOrder: 11, SetOrder: 55, Set: "Foundation", Ref: "Deuteronomy 6:5"},
	{BibleOrder: 10, SetOrder: 56, Set: "Foundation", Ref: "Leviticus 19:18b"},
	{BibleOrder: 64, SetOrder: 57, Set: "Foundation", Ref: "Philippians 2:3"},
	{BibleOrder: 65, SetOrder: 58, Set: "Foundation", Ref: "Philippians 2:4"},
	{BibleOrder: 43, SetOrder: 59, Set: "Foundation", Ref: "Proverbs 17:17"},
	{BibleOrder: 57, SetOrder: 60, Set: "Foundation", Ref: "1 Corinthians 13:4"},
	{BibleOrder: 58, SetOrder: 61, Set: "Foundation", Ref: "1 Corinthians 13:5"},
	{BibleOrder: 59, SetOrder: 62, Set: "Foundation", Ref: "1 Corinthians 13:6"},
	{BibleOrder: 60, SetOrder: 63, Set: "Foundation", Ref: "1 Corinthians 13:7"},
	{BibleOrder: 75, SetOrder: 64, Set: "Foundation", Ref: "1 Peter 5:8"},
	{BibleOrder: 54, SetOrder: 65, Set: "Foundation", Ref: "Romans 3:23"},
	{BibleOrder: 68, SetOrder: 66, Set: "Foundation", Ref: "Philippians 4:13"},
	{BibleOrder: 55, SetOrder: 67, Set: "Foundation", Ref: "Romans 6:23"},
	{BibleOrder: 27, SetOrder: 68, Set: "Foundation", Ref: "Psalm 118:24"},
	{BibleOrder: 66, SetOrder: 69, Set: "Foundation", Ref: "Philippians 2:14"},
	{BibleOrder: 42, SetOrder: 70, Set: "Foundation", Ref: "Proverbs 16:24"},
	{BibleOrder: 51, SetOrder: 71, Set: "Foundation", Ref: "Luke 6:38"},
	{BibleOrder: 69, SetOrder: 72, Set: "Foundation", Ref: "Hebrews 13:5"},
	{BibleOrder: 72, SetOrder: 73, Set: "Foundation", Ref: "James 1:19b"},
	{BibleOrder: 29, SetOrder: 74, Set: "Foundation", Ref: "Psalm 119:10"},
	{BibleOrder: 30, SetOrder: 75, Set: "Foundation", Ref: "Psalm 119:11"},
	{BibleOrder: 63, SetOrder: 76, Set: "Foundation", Ref: "Ephesians 6:10"},
}
